DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_NIC VARCHAR2(20) NOT NULL,
	MEMBER_EMAIL VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(20),
	MEMBER_TEL VARCHAR2(20),
	MEMBER_BIRTH VARCHAR2(20),
	MEMBER_CON VARCHAR2(20),
	MEMBER_REGDATE DATE NOT NULL,
	MEMBER_DEL VARCHAR2(2) NOT NULL,
	MEMBER_ROLE VARCHAR2(10) NOT NULL,
	MEMBER_DAILY VARCHAR2(2) NOT NULL,
	CONSTRAINT MEM_NIC UNIQUE(MEMBER_NIC),
	CONSTRAINT MEM_ROLE UNIQUE(MEMBER_ROLE)
);
