DROP SEQUENCE CALSEQ;
DROP TABLE CALENDAR;

CREATE SEQUENCE CALSEQ;

CREATE TABLE CALENDAR(
	CAL_NO NUMBER PRIMARY KEY,
	MEMBER_NO NUMBER NOT NULL,
	CAL_TITLE VARCHAR2(500) NOT NULL,
	CAL_CONTENT VARCHAR2(4000) NOT NULL,
	CAL_MDATE VARCHAR2(300) NOT NULL,
	CAL_REGDATE VARCHAR2(300) NOT NULL,
	CONSTRAINT CAL_FK01 FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
);