DROP TABLE EDU_WORD;

CREATE TABLE EDU_WORD(
	EDU_NO NUMBER NOT NULL,
	AUDIO_NO NUMBER NOT NULL,
	IMAGE_NO NUMBER NOT NULL,
	EW_CONTENT VARCHAR2(2000) NOT NULL,
	EW_ANSWER VARCHAR2(2000) NOT NULL,
	CONSTRAINT EW_FK01 FOREIGN KEY (EDU_NO) REFERENCES EDU(EDU_NO),
	CONSTRAINT EW_FK02 FOREIGN KEY (AUDIO_NO) REFERENCES AUDIO(AUDIO_NO),
	CONSTRAINT EW_FK03 FOREIGN KEY (IMAGE_NO) REFERENCES IMAGE(IMAGE_NO)
);