DROP TABLE EDU_SPEAK;

CREATE TABLE EDU_SPEAK(
	MEMBER_NO NUMBER NOT NULL,
	EDU_NO NUMBER NOT NULL,
	AUDIO_NO NUMBER NOT NULL,
	ES_SCORE NUMBER NOT NULL,
	CONSTRAINT ES_FK01 FOREIGN KEY (MEMBER_NO) REFERENCES MEMBER(MEMBER_NO),
	CONSTRAINT ES_FK02 FOREIGN KEY (EDU_NO) REFERENCES EDU(EDU_NO),
	CONSTRAINT ES_FK03 FOREIGN KEY (AUDIO_NO) REFERENCES AUDIO(AUDIO_NO)
);