CREATE TABLE EDU_WORD(
	EDU_NO NUMBER NOT NULL,
	EDU_GRADE VARCHAR2(50) NOT NULL,
	EW_LEVEL NUMBER NOT NULL,
	EW_CONTENT VARCHAR2(2000) NOT NULL,
	CONSTRAINT EW_FK01 FOREIGN KEY (EDU_NO) REFERENCES EDU(EDU_NO)
);

SELECT * FROM EDU_WORD WHERE EDU_NO = 2 ORDER BY EW_LEVEL;

INSERT INTO EDU_WORD
VALUES(7, '초급', 3, '톰씨는 맥주를 좋아해요.');

UPDATE EDU_WORD SET EW_LEVEL = 4 WHERE EW_CONTENT = '여';

DROP TABLE EDU_WORD;

SELECT EDU_NO, EDU_GRADE, EW_LEVEL, EW_CONTENT
		FROM EDU_WORD
		WHERE EDU_GRADE = '입문'
		ORDER BY EW_LEVEL;

		
DELETE FROM EDU_WORD WHERE EDU_NO = 5;
SELECT * FROM MEMBER;