DROP SEQUENCE MENTOANSWERSEQ
DROP TABLE MENTO_ANSWER

CREATE SEQUENCE MENTOANSWERSEQ;

--댓글번호, 글번호, 멘토번호, 회원번호, 내용, 작성일

CREATE TABLE MENTO_ANSWER(
	MA_NO NUMBER NOT NULL,
	DB_NO NUMBER NOT NULL,
	MENTO_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	MA_CONTENT VARCHAR2(4000) NOT NULL,
	MA_DATE DATE NOT NULL,
	
	CONSTRAINT MA_NO_PK PRIMARY KEY(MA_NO),
	CONSTRAINT DAILY_FK_DB_NO FOREIGN KEY(DB_NO)
		REFERENCES DAILY_BOARD(DB_NO),
	CONSTRAINT MENTO_FK_MENTO_NO FOREIGN KEY(MENTO_NO)
		REFERENCES MENTO(MENTO_NO),
	CONSTRAINT MEMBER_FK_MEMBERNO3 FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE
)

SELECT * FROM MENTO_ANSWER