DROP SEQUENCE DAILYBOARDSEQ
DROP TABLE DAILY_BOARD

CREATE SEQUENCE DAILYBOARDSEQ;

--글번호, 회원번호, 제목, 내용, 작성일, 첨삭여부

CREATE TABLE DAILY_BOARD(
	DB_NO NUMBER NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	DB_TITLE VARCHAR2(500) NOT NULL,
	DB_CONTENT VARCHAR2(4000) NOT NULL,
	DB_DATE DATE NOT NULL,
	DB_ANSWER VARCHAR2(20) NOT NULL,
	
	CONSTRAINT DB_NO_PK PRIMARY KEY(DB_NO),
	CONSTRAINT MEMBER_FK_MEMBER_NO FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO) ON DELETE CASCADE	
)

INSERT INTO DAILY_BOARD
VALUES(DAILYBOARDSEQ.NEXTVAL, 1, 'TEST-TITLE', 'TEST-CONTENT',
       SYSDATE, 'N')
INSERT INTO DAILY_BOARD
VALUES(DAILYBOARDSEQ.NEXTVAL, 1, 'TEST2', 'TEST-CONTENT2',
       SYSDATE, 'N')
       
SELECT * FROM DAILY_BOARD       