DROP SEQUENCE MENTOSEQ
DROP TABLE MENTO

CREATE SEQUENCE MENTOSEQ;

--멘토번호, 경력, 주소, 멤버번호(관리하는 멤버)

CREATE TABLE MENTO(
	MENTO_NO NUMBER NOT NULL,
	MENTO_CAREER VARCHAR2(500) NOT NULL,
	MENTO_ADDR VARCHAR2(2000) NOT NULL,
	MEMBER_NO NUMBER NOT NULL,
	
	CONSTRAINT MENTO_PK_MENTO_NO PRIMARY KEY(MENTO_NO),
	CONSTRAINT MEMBER_FK_MEMBERNO2 FOREIGN KEY(MEMBER_NO)
		REFERENCES MEMBER(MEMBER_NO)
)

SELECT * FROM MENTO

INSERT INTO MENTO
VALUES(MENTOSEQ.NEXTVAL, '신입', '경기도 일산', 1)