DROP SEQUENCE MEMBERSEQ;
DROP TABLE MEMBER;

CREATE SEQUENCE MEMBERSEQ;
CREATE TABLE MEMBER(
	MEMBER_NO NUMBER PRIMARY KEY,
	MEMBER_NAME VARCHAR2(20) NOT NULL,
	MEMBER_NIC VARCHAR2(20) NOT NULL,
	MEMBER_EMAIL VARCHAR2(20) NOT NULL,
	MEMBER_PW VARCHAR2(20),
	MEMBER_TEL VARCHAR2(20),
	MEMBER_BIRTH VARCHAR2(20),
	MEMBER_CON VARCHAR2(20),
	MEMBER_REGDATE DATE NOT NULL,
	MEMBER_DEL VARCHAR2(2) NOT NULL,
	MEMBER_ROLE VARCHAR2(10) NOT NULL,
	MEMBER_DAILY VARCHAR2(2) NOT NULL,
	MENTO_NO NUMBER,
	MEMBER_KEY VARCHAR2(500),
	
	CONSTRAINT MEM_NIC UNIQUE(MEMBER_NIC),
	CONSTRAINT MEN_NO FOREIGN KEY(MENTO_NO) REFERENCES MEMBER(MEMBER_NO)
);

ALTER TABLE MEMBER MODIFY (MEMBER_PW VARCHAR2(500));

SELECT MEMBER_NO, MEMBER_NAME, MEMBER_NIC, MEMBER_EMAIL, MEMBER_PW, MEMBER_TEL, MEMBER_BIRTH,
	   MEMBER_CON, MEMBER_REGDATE, MEMBER_DEL, MEMBER_ROLE, MEMBER_DAILY, MENTO_NO, MEMBER_KEY
FROM MEMBER
ORDER BY MEMBER_NO DESC;

SELECT * FROM MEMBER ORDER BY MEMBER_NO DESC;

INSERT INTO MEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'user', '유저', 'user@user.com', 'user', '010-0000-0000', '19951110', 
		'ASIA', SYSDATE, 'N', 'USER', 'N', NULL, 'Y');

INSERT INTO MEMBER
VALUES(MEMBERSEQ.NEXTVAL, 'admin', '관리자', 'admin@admin.com', 'admin', '010-0000-0000', '19951110', 
		'ASIA', SYSDATE, 'N', 'ROLE_ADMIN', 'N', NULL, 'N');





