DROP TABLE ORDER_DAILY;
DROP TABLE ORDERSEQ;

CREATE SEQUENCE ORDERSEQ;
CREATE TABLE ORDER_DAILY (
	ORDER_NO NUMBER PRIMARY KEY,	
	MEMBER_NO NUMBER NOT NULL,
	DS_NO NUMBER NOT NULL,
	ORDER_COUNT NUMBER NOT NULL,
	ORDER_DATE DATE NOT NULL,
	ORDER_EDATE DATE NOT NULL,
	
	CONSTRAINT MEM_NO FOREIGN KEY(MEMBER_NO) REFERENCES MEMBER(MEMBER_NO)
	
	
);

SELECT * FROM ORDER_DAILY;

CONSTRAINT D_NO FOREIGN KEY(DS_NO) REFERENCES DAILY_SERVICE(DS_NO)